# Generated by Django 4.2.7 on 2023-11-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150, verbose_name='ваш номер телефона')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='машина')),
            ],
        ),
    ]
